name: denn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_1000
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - boost-cpp=1.70.0=h75728bb_2
  - boto3=1.12.24=pyh8c360ce_0
  - botocore=1.15.24=pyh8c360ce_0
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37hc8dfbb8_1
  - cffi=1.13.2=py37h33e799b_0
  - cmake=3.16.2=hd28f656_1
  - cryptography=2.8=py37he655712_2
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.15.2=py37_0
  - eigen=3.3.7=ha1b3eb9_1001
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=h4a8c4bd_1004
  - fastcache=1.1.0=py37h0b31af3_0
  - fenics=2019.1.0=py37_8
  - fenics-dijitso=2019.1.0=py_8
  - fenics-dolfin=2019.1.0=py37hb0736e2_8
  - fenics-ffc=2019.1.0=py_8
  - fenics-fiat=2019.1.0=py_8
  - fenics-libdolfin=2019.1.0=h765d0ea_8
  - fenics-ufl=2019.1.0=py_8
  - freetype=2.10.0=h24853df_1
  - gmp=6.1.2=h0a44026_1000
  - gmpy2=2.1.0b1=py37h4160ff4_0
  - hdf5=1.10.5=mpi_mpich_h3734b49_1004
  - hypre=2.18.2=hc9ba2bc_0
  - icu=64.2=h6de7cb9_1
  - idna=2.9=py_1
  - importlib_metadata=1.2.0=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.10.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jmespath=0.9.5=py_0
  - jpeg=9c=h1de35cc_1001
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.3=py37_1
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.3=py_0
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py37ha1b3eb9_0
  - krb5=1.16.4=h1752a42_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=h16faf7d_0
  - libcxx=9.0.1=1
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - libiconv=1.15=h01d97ff_1005
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h3d69b6c_4
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.17=h01d97ff_0
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.1.0=ha78913b_1
  - libuv=1.34.0=h0b31af3_0
  - llvm-openmp=9.0.0=h40edb58_0
  - lz4-c=1.8.3=h6de7cb9_1001
  - markupsafe=1.1.1=py37h0b31af3_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h11da6c2_1
  - metis=5.1.0=h4a8c4bd_1005
  - mistune=0.8.4=py37h0b31af3_1000
  - mkl=2019.4=233
  - more-itertools=8.0.2=py_0
  - mpc=1.1.0=h4160ff4_1006
  - mpfr=4.0.2=h44b798e_0
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py37hafcb60b_0
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.1.0=py_0
  - mumps-include=5.2.1=5
  - mumps-mpi=5.2.1=hcf7f05f_5
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - ninja=1.9.0=ha1b3eb9_1
  - notebook=6.0.1=py37_0
  - numpy=1.17.3=py37hde6bac1_0
  - olefile=0.46=py_0
  - openssl=1.1.1e=h0b31af3_0
  - pandas=0.25.3=py37h4f17bb1_0
  - pandoc=2.8.1=0
  - pandocfilters=1.4.2=py_1
  - parmetis=4.0.3=hbc1d92b_1004
  - parso=0.5.1=py_0
  - petsc=3.12.3=h6ceeb6d_0
  - petsc4py=3.12.0=py37h833b260_4
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.2.1=py37h43b43f3_1
  - pip=19.3.1=py37_0
  - pkg-config=0.29.2=hdc84dc8_1006
  - pkgconfig=1.3.1=py37_1002
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptscotch=6.0.8=h8c5ff5d_1
  - ptyprocess=0.6.0=py_1001
  - pybind11=2.4.3=py37ha1b3eb9_0
  - pycparser=2.19=py37_1
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.5=py_0
  - pyrsistent=0.15.6=py37h0b31af3_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.3=h5c2c468_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.3.1=py3.7_0
  - pytz=2019.3=py_0
  - pyyaml=5.3=py37h0b31af3_0
  - pyzmq=18.1.1=py37h4bf09a9_0
  - readline=8.0=hcfe32e1_0
  - rhash=1.3.6=h1de35cc_1001
  - s3transfer=0.3.3=py37_0
  - scalapack=2.0.2=h4fb7227_1007
  - scipy=1.3.2=py37h82752d6_0
  - scotch=6.0.8=h703c93e_1
  - send2trash=1.5.0=py_0
  - setuptools=42.0.2=py37_0
  - six=1.13.0=py37_0
  - slepc=3.12.2=hefb7033_0
  - slepc4py=3.12.0=py37h00bfe04_1
  - sqlite=3.30.1=h93121df_0
  - suitesparse=5.6.0=h0e59142_0
  - superlu=5.2.1=hc209f47_1206
  - superlu_dist=6.2.0=h32cdba5_1
  - sympy=1.5.1=py37_0
  - tbb=2019.9=ha1b3eb9_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - torchvision=0.4.2=py37_cpu
  - tornado=6.0.3=py37h0b31af3_0
  - tqdm=4.40.0=py_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.2.2=h0b31af3_1
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.4=he7fca8b_1
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - bayesian-optimization==1.1.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - filelock==3.0.12
    - funcsigs==1.0.2
    - grpcio==1.27.2
    - joblib==0.14.1
    - multidict==4.7.5
    - packaging==20.1
    - pluggy==0.13.1
    - protobuf==3.11.3
    - psutil==5.7.0
    - py==1.8.1
    - pytest==5.3.5
    - ray==0.8.1
    - redis==3.4.1
    - requests==2.23.0
    - scikit-learn==0.22.2.post1
    - setproctitle==1.1.10
    - tabulate==0.8.6
    - urllib3==1.25.8
    - yarl==1.4.2
