name: denn
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - boost-cpp=1.70.0
  - boto3=1.12.24
  - botocore=1.15.24
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - cmake=3.16.2
  - cryptography=2.8
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - docutils=0.15.2
  - eigen=3.3.7
  - entrypoints=0.3
  - expat=2.2.5
  - fastcache=1.1.0
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - freetype=2.10.0
  - gmp=6.1.2
  - gmpy2=2.1.0b1
  - hdf5=1.10.5
  - hypre=2.18.2
  - icu=64.2
  - idna=2.9
  - importlib_metadata=1.2.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.10.1
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jinja2=2.10.3
  - jmespath=0.9.5
  - jpeg=9c
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter_client=5.3.3
  - jupyter_core=4.6.1
  - jupyterlab=1.2.3
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libcxx=9.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libuv=1.34.0
  - llvm-openmp=9.0.0
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - metis=5.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - more-itertools=8.0.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.2
  - mpmath=1.1.0
  - mumps-include=5.2.1
  - mumps-mpi=5.2.1
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.1
  - numpy=1.17.3
  - olefile=0.46
  - openssl=1.1.1f
  - pandas=0.25.3
  - pandoc=2.8.1
  - pandocfilters=1.4.2
  - parmetis=4.0.3
  - parso=0.5.1
  - petsc=3.12.3
  - petsc4py=3.12.0
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - pkg-config=0.29.2
  - pkgconfig=1.3.1
  - plotly=4.6.0
  - plotly-orca=1.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptscotch=6.0.8
  - ptyprocess=0.6.0
  - pybind11=2.4.3
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.3.1
  - pytz=2019.3
  - pyyaml=5.3
  - pyzmq=18.1.1
  - readline=8.0
  - retrying=1.3.3
  - rhash=1.3.6
  - s3transfer=0.3.3
  - scalapack=2.0.2
  - scipy=1.3.2
  - scotch=6.0.8
  - send2trash=1.5.0
  - setuptools=42.0.2
  - six=1.13.0
  - slepc=3.12.2
  - slepc4py=3.12.0
  - sqlite=3.30.1
  - suitesparse=5.6.0
  - superlu=5.2.1
  - superlu_dist=6.2.0
  - sympy=1.5.1
  - tbb=2019.9
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - torchvision=0.4.2
  - tornado=6.0.3
  - tqdm=4.40.0
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - bayesian-optimization==1.1.0
    - beautifulsoup4==4.8.2
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - filelock==3.0.12
    - flask==1.1.1
    - flask-compress==1.4.0
    - funcsigs==1.0.2
    - grpcio==1.27.2
    - hiplot==0.1.7.post3
    - itsdangerous==1.1.0
    - joblib==0.14.1
    - multidict==4.7.5
    - packaging==20.1
    - pluggy==0.13.1
    - protobuf==3.11.3
    - psutil==5.7.0
    - py==1.8.1
    - pytest==5.3.5
    - ray==0.8.1
    - redis==3.4.1
    - requests==2.23.0
    - scikit-learn==0.22.2.post1
    - setproctitle==1.1.10
    - soupsieve==2.0
    - tabulate==0.8.6
    - urllib3==1.25.8
    - werkzeug==1.0.1
    - yarl==1.4.2
